# Site
name: "sysa"
title: "shoaiyb sysa"
description: "Get free blogging tips & tricks."
logo: 'assets/images/logo.svg'
favicon: 'assets/images/favicon-32Ã—32.png'
baseurl: /
google_analytics: 'UA-xxxxxxxx-1'
disqus: 'shoaiyb'
mailchimp-list: 'https://mailto:support@flatbum.ga'
include: ["_pages"]
permalink: /:title/
email: contact@sysa.ml

# Authors
authors:
  shoaiyb:
    name: shoaiyb sysa
    display_name: sysa
    gravatar: 9b70db5a5cdfd531438f63ff4cae215a
    email: contact@sysa.ml
    web: https://sysa.ml/about/
    instagram: https://instagram.com/sysa_shoaiyb
    description: "I'm shoaiyb sysa part time blogger and a youtuber, I'm self taught backend and frontend developer, I'm here just to welcome and help those newbies on how they're going to get started in this online world."
 # john:
  #  name: John
  #  display_name: John    
  #  avatar: 'assets/images/avatar.png'
  #  gravatar: b1cc14991db7a456fcd761680bbc8f81
  #  email: wowthemesnet@gmail.com
  #  web: https://www.wowthemes.net
  #  twitter: https://twitter.com/wowthemesnet
  #  description: "This is the author box. Write a short description of the author here. You are currently previewing Mediumish demo, a Jekyll template compatible with Github pages."

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
  - jekyll-figure
  - jekyll-admin
  - jekyll-redirect-from
    
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
highlighter: none
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true



# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "enabled"

# Post Author Box ("enabled" or "disabled")
authorbox: "enabled"

# Sass
sass:
  sass_dir: _sass
  style: compressed

exclude: [LICENSE, Gemfile, Gemfile.lock]
